### ISSUE TITLE
Allow 'when' argument to be a list of items

### ISSUE THREAD

**Issue by svniemeijer** [stcorp/legato#3]
This would allow us to specify something like:

```
twice_a_day_task:
  type: time
  when:
    - every day at 08:00
    - every day at 19:00
```
