### ISSUE TITLE
Exclude 'include' entries for --task and --list options

### ISSUE THREAD

**Issue by svniemeijer** [stcorp/legato#4]
For configuration entries like:

```
include_file:
  include: extra_config_file.yaml

include_dir:
  include: extra_config_dir/
```

We should exclude the `include_file` and `include_dir` items in the task listing and explicit task execution.
